name: CI
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Archive Build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist
    
